Models/MeetingInfo.cs
namespace MeetingApp.Models
{
    public class MeetingInfo
    {
        public int Id { get; set; }
        public string? Location { get; set; }
        public DateTime Date{ get; set; }
        public int NumberOfPeople { get; set; }




    }
}

Models/Repository.cs
namespace MeetingApp.Models
{
    public class Repository
    {
        private static List<UserInfo> _users = new();
        public static List<UserInfo> Users { get { return _users; } }

        public static void CreateUser(UserInfo user)
        {
            _users.Add(user);
        }
    }
}

Models/UserInfo.cs
namespace MeetingApp.Models
{
    public class UserInfo
    {
        public string? Name { get; set; }
        public string? Phone { get; set; }
        public string? Email { get; set; }
        public bool WillAttend { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MeetingApp.Models;

namespace MeetingApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            int saat = DateTime.Now.Hour;
            ViewBag.Selamlama = saat > 12 ? "İyi Günler" : "Günaydın";

            var  info = new MeetingInfo(){
                Id = 1,
                Location = "Online",
                Date = new DateTime(2024, 1, 20)
            };
            return View();
        }
    }
}

Controllers/MeetingController.cs
using Microsoft.AspNetCore.Mvc;
using MeetingApp.Models;

namespace MeetingApp.Controllers
{
    public class MeetingController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Apply()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Apply(UserInfo model)
        {
            Repository.CreateUser(model);
            ViewBag.UserCount = Repository.Users.Where(u => u.WillAttend == true).Count();
            return View("Thanks", model);
        }

        [HttpGet]
        public IActionResult List()
        {
            return View();
        }
    }
}

Views/Home/Index.cshtml
<h1>@ViewBag.Selamlama</h1>
<p>Toplantı katılım durumunuzu bildiriniz</p>
<a class="btn btn-sm btn-outline-primary" asp-controller="Meeting" asp-action="Apply"> Başvuru Yap </a>

Views/Meeting/Apply.cshtml
@model UserInfo

<h1>Toplantı katılım formu</h1>
<form method="post" action="/Meeting/Apply" novalidate>
    <div asp-validation-summary="All">
        <div class="mb-3">
            <label asp-for="Name" class="form-label">Ad Soyad</label>
            <input asp-for="Name" class="form-control">
        </div>
        <div class="mb-3">
            <label asp-for="Phone" class="form-label">Telefon</label>
            <input asp-for="Phone" class="form-control">
        </div>
        <div class="mb-3">
            <label asp-for="Email" class="form-label">Email</label>
            <input asp-for="Email" class="form-control">
        </div>
        <div class="mb-3">
            <label asp-for="WillAttend" class="form-label">Katılım Durumu</label>
            <select asp-for="WillAttend" class="form-select">
                <option value="True">Evet Geliyorum</option>
                <option value="False">Hayır Gelmiyorum</option>
            </select>
        </div>
    </div>
    <button class="btn btn-primary" type="submit">Kaydet</button>

</form>

Views/Meeting/Index.cshtml
<h1 class="h4">Toplantı özeti</h1>
<p>Toplantıya sizinle birlikte 20 kişi katılıyor </p>
<a class="btn btn-sm btn-outline-primary">Katılımcıları Listele</a>

Views/Meeting/List.cshtml
<h1 class="h4">Toplantı katılım listesi</h1>

<table class="table table-bordered">
    <thead>
        <tr>
            <td>Ad</td>
            <td>Email</td>
            <td>Katıım Durumu</td>
            <td></td>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td>Esra Evren</td>
            <td>info@esraevren.com</td>
            <td>Evet</td>
            <td><a class="btn btn-sm btn-primary" href="#">Detay</a></td>
        </tr>
        <tr>
            <td>Burak Evren</td>
            <td>info@burakevren.com</td>
            <td>Evet</td>
            <td><a class="btn btn-sm btn-primary"  href="#">Detay</a></td>
        </tr>
    </tbody>
</table>

Views/Meeting/Thanks.cshtml
@model UserInfo

<main class="text-center">
 
if(Model.WillAttend ==true)


</main>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/css/bootstrap.min.css"
        integrity="sha512-jnSuA4Ss2PkkikSOLtYs8BlYIeeIK1h99ty4YfvRPAlzr377vr3CXDb7sb7eEEBYjDtcYj+AjBH3FLv5uSJuXg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>Document</title>
</head>

<body>
    <div class="bg-primary text-white p-2 text-center">
        MeetingApp
    </div>

    <div class="container mt-3">
        <div class="row">
            <div class="col-lg-6 mx-auto text-center">
                <div class="card">
                    <div class="card-body">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>